version: "3.9"

services:
  server:
    build: ./server
    container_name: orebi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    restart: always

  client:
    build: ./client
    container_name: orebi-client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    restart: always
    depends_on:
      - server

  admin:
    build: ./admin
    container_name: orebi-admin
    ports:
      - "3001:80"
    env_file:
      - ./admin/.env
    restart: always
    depends_on:
      - server
